# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': "OpenFire / Planning",
    'version': '16.0.1.6.1',
    'license': 'AGPL-3',
    'author': "OpenFire",
    'category': "OpenFire",
    'summary': "Gestion des interventions",
    'website': "https://www.openfire.fr",
    'depends': [
        'calendar',
        'hr',
        'l10n_fr_department',
        'of_sale_order_dates',
        'of_geolocalize',
        'of_sale_stock',
    ],
    'data': [
        'data/data.xml',
        'data/report_paperformat.xml',
        'data/cron_planning.xml',
        'data/email_planning.xml',
        'reports/report_intervention_report.xml',  # required before email_intervention.xml for email template
        'data/email_intervention.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/of_sector_views.xml',
        'views/of_planning_intervention_line_views.xml',
        'views/of_planning_intervention_template_views.xml',
        'views/of_planning_tag_views.xml',
        'views/of_planning_task_views.xml',
        'views/of_planning_team_views.xml',
        'views/of_image_views.xml',
        'views/hr_employee_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/sale_order_line_views.xml',
        'views/stock_picking_views.xml',
        'views/procurement_group_views.xml',
        'views/calendar_event_views.xml',
        'views/res_config_settings_views.xml',
        'views/menuitems.xml',
        'reports/report_intervention_template.xml',
        'reports/report_intervention_sheet.xml',
        'reports/report_planning_general_week.xml',
        'reports/report_planning_week.xml',
        'reports/report_planning_day.xml',
        'wizards/of_planning_print_wizard_views.xml',
        'views/ir_action_server.xml',
    ],
    'assets': {
        'web.assets_backend': ['of_planning/static/src/xml/planning_calendar_popover.xml'],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
}
