# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': "OpenFire / Demande d'intervention",
    'version': '16.0.1.4.1',
    'license': 'AGPL-3',
    'author': "OpenFire",
    'category': "OpenFire",
    'summary': "Gestion des demandes d'interventions",
    'website': "https://www.openfire.fr",
    'depends': [
        'of_planning',
        'of_geolocalize',
        'sales_team',
    ],
    'data': [
        'data/ir_sequence.xml',
        'data/of_service_request_type.xml',
        'data/of_service_request_stage.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/of_service_request_tag_views.xml',
        'views/of_service_request_stage_views.xml',
        'views/of_service_request_views.xml',
        'views/calendar_event_views.xml',
        'views/of_planning_task_views.xml',
        'views/of_planning_intervention_template_views.xml',
        'views/sale_order_views.xml',
        'views/res_partner_views.xml',
        'views/menuitems.xml',
        'reports/of_service_request_templates.xml',
        'data/mail_template.xml',
        'wizards/of_service_request_create_intervention_wizard_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
