# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from . import update
from . import base_config_settings
from . import base
from . import ir_http
from . import ir_attachment
from . import res_company
from . import ir_mail_server
from . import ir_model_field
from . import ir_module
from . import ir_ui_menu
from . import mail_message
from . import mail_template
from . import of_form_readonly
from . import of_image
from . import of_log_message
from . import of_read_group
from . import of_res_partner_phone
from . import of_sanitize_query
from . import res_partner
from . import product_product
from . import product_template
from . import res_bank
from . import res_config
from . import res_groups
from . import res_partner_bank
from . import res_partner_title
from . import res_users
from . import version_registery
