# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import fields, models


class ResConfigSettings(models.TransientModel):
    _inherit = "res.config.settings"

    of_wizville_sftp_host = fields.Char(
        string="FTP server address", config_parameter="of.wizville.base.wizville_sftp_host"
    )
    of_wizville_sftp_port = fields.Char(
        string="FTP server port", config_parameter="of.wizville.base.wizville_sftp_port"
    )
    of_wizville_sftp_user = fields.Char(string="Login", config_parameter="of.wizville.base.wizville_sftp_user")
    of_wizville_sftp_password = fields.Char(
        string="Password", config_parameter="of.wizville.base.wizville_sftp_password"
    )
    of_wizville_sftp_deposit_directory = fields.Char(
        string="Deposit folder for generated files",
        help="Corresponds to the location where files generated by OpenFire ,must be filed on the sftp Wizville",
        config_parameter="of.wizville.base.wizville_sftp_deposit_directory",
    )
    of_wizville_sftp_pickup_directory = fields.Char(
        string="Score files folder",
        help="Corresponds to the location where the files generated by Wizville are to be retrieved",
        config_parameter="of.wizville.base.wizville_sftp_pickup_directory",
    )
    of_wizville_export_filename = fields.Char(
        string="Name of export file",
        config_parameter="of.wizville.base.wizville_export_filename",
        help="Name of the file to be generated by OpenFire and sent to Wizville. This value will be evaluated by Odoo "
        "with a custom context.",
    )
    of_wizville_import_filename = fields.Char(
        string="Name of the import file",
        config_parameter="of.wizville.base.wizville_import_filename",
        help="Name of the file to be retrieved by OpenFire from Wizville. This value will be evaluated by Odoo with a "
        "custom context.",
    )
    of_wizville_satisfaction_question = fields.Integer(
        string="No. question for 'Overall satisfaction'",
        config_parameter="of.wizville.base.wizville_satisfaction_question",
    )
    of_wizville_nps_score_question = fields.Integer(
        string="Question no. for 'NPS Score'", config_parameter="of.wizville.base.wizville_nps_score_question"
    )
