# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': "OpenFire / Product Datastore",
    'version': "16.0.1.0.0",
    "license": 'AGPL-3',
    'author': "OpenFire",
    "website": "https://www.openfire.fr",
    'category': "OpenFire",
    'summary': "Gestion des produits centralisés",
    'depends': [
        'of_datastore_connector',
        'of_datastore',
        'of_product_pack',  # of_product_brand > of_product
        'stock',
        'purchase',
        'of_import',
        'of_utils',
        'of_purchase_stock',
        'of_equipment',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'wizards/of_datastore_import_brand.xml',
        'wizards/of_datastore_update_product.xml',
        'wizards/of_remove_unused_products.xml',
        'wizards/wizard_of_datastore_brand_ask.xml',
        'wizards/of_datastore_display_stock_wizard_views.xml',
        'views/of_datastore_brand_views.xml',
        'views/of_datastore_supplier_views.xml',
        'views/of_product_brand_views.xml',
        'views/product_product_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/product_product_views.xml',
        'views/menuitems.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
