# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': "OpenFire / Ventes",
    'version': '16.0.1.3.0',
    'license': 'AGPL-3',
    'author': "OpenFire",
    'website': "https://www.openfire.fr",
    'category': "OpenFire",
    'summary': "Personnalisation des ventes",
    'depends': [
        'of_account',  # of_account > of_product_brand > of_product
        "of_account_tax",
        'of_base_location',
        'sale_margin',
        'sale_crm',
        'sale_stock',
        'of_utils',
        'of_utm',
        'remove_odoo_enterprise',
    ],
    'external_dependencies': {
        'python': ['pdfminer', 'pypdftk', 'pyPdf'],
    },
    'data': [
        'data/ir_config_parameter.xml',
        'data/mail_message_subtype.xml',
        'security/ir.model.access.csv',
        'security/res_groups.xml',
        'views/res_config_settings_views.xml',
        'views/res_company_views.xml',
        'views/account_move_views.xml',
        'views/sale_order_views.xml',
        'views/sale_order_line_views.xml',
        'views/product_category_views.xml',
        'views/res_partner_views.xml',
        'report/report_sale_order.xml',
        'report/report_account_move.xml',
        'wizards/of_sale_order_add_quote_views.xml',
        'report/of_report_sale_order_list.xml',
        'report/sale_report_views.xml',
        'wizards/sale_make_invoice_advance_views.xml',
        'wizards/of_sale_order_verification_views.xml',
        'wizards/of_sale_order_confirmation_views.xml',
        'wizards/of_res_partner_check_duplications_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'of_sale/static/src/**/*',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
