# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': u"OpenFire / Ventes",
    'version': '16.0.1.0.0',
    'license': 'AGPL-3',
    'author': "OpenFire",
    'website': "https://www.openfire.fr",
    'category': "OpenFire",
    'summary': "Personnalisation des ventes",
    'description': "",
    'depends': [
        # "of_account_invoice_report",  # TODO: uncomment when of_account is migrated
        # "of_account_tax",  # TODO: uncomment when of_account is migrated
        'of_base_location',
        'of_custom_document',
        'of_product',
        'sale',
        'sale_margin',
        'sale_crm',
        'sale_stock',
        'of_utils',
        'of_utm',
        'remove_odoo_enterprise',
    ],
    'external_dependencies': {
        'python': ['pdfminer', 'pypdftk', 'pyPdf'],
    },
    'data': [
        'data/ir_config_parameter.xml',
        'security/ir.model.access.csv',
        'security/res_groups.xml',
        'views/res_config_settings_views.xml',
        'views/res_company_views.xml',
        'views/account_move_views.xml',
        'views/sale_order_views.xml',
        'views/sale_order_line_views.xml',
        'views/product_category_views.xml',
        'views/res_partner_views.xml',
        'views/payment_term_views.xml',
        'report/report_sale_order.xml',
        'report/report_account_move.xml',
        'wizard/of_sale_order_add_quote_views.xml',
        # 'report/of_report_sale_order_list.xml',
        'report/sale_report_views.xml',
        'wizard/sale_make_invoice_advance_views.xml',
        'wizard/of_sale_order_verification_views.xml',
        'wizard/of_sale_order_confirmation_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
