# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': "OpenFire / Base",
    'version': '16.0.1.0.1',
    'license': 'AGPL-3',
    'author': "OpenFire",
    'category': 'OpenFire',
    'sequence': 15,
    'summary': "Base module for OpenFire",
    'website': 'https://www.openfire.fr',
    'depends': [
        'base',
        'base_iban',
        'base_vat',
        'crm',
        'product',
        'mail',
        'contacts',
        'base_view_inheritance_extension',
        'of_web_widgets',
    ],
    'data': [
        'data/ir_cron.xml',
        'data/ir_config_parameter.xml',
        'data/report_paperformat.xml',
        'data/of_sanitize_query.xml',
        'security/of_base_security.xml',
        'security/ir.model.access.csv',
        'views/base_config_settings_views.xml',
        'views/mail_message_views.xml',
        'views/mail_template_views.xml',
        'views/mail_views.xml',
        'views/menus_actions_views.xml',
        'views/of_connector_config_settings_views.xml',
        'views/of_image_views.xml',
        'views/of_log_message_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_bank_views.xml',
        'views/res_partner_title_views.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/login_templates.xml',
        'views/inactive_user_templates.xml',
        'wizards/base_module_upgrade_view.xml',
        'wizards/mail_compose_message_views.xml',
        'wizards/of_popup_wizard_view.xml',
        'wizards/of_res_partner_check_duplications_views.xml',
        'wizards/of_html_sanitize_views.xml',
        'templates/of_report_footer.xml',
    ],
    'external_dependencies': {
        'python': [
            'schwifty',
        ],
    },
    'assets': {
        'web.assets_backend': [
            'of_base/static/src/js/user_menu_item.js',
            'of_base/static/src/js/history_back.js',
            'of_base/static/src/js/settings_form_compiler.js',
            'of_base/static/src/js/code_version.js',
            'of_base/static/src/xml/code_version.xml',
            'of_base/static/src/less/of_base.less',
        ],
        'web.report_assets_common': [
            'of_base/static/src/scss/style.scss',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'pre_init_hook': 'pre_init_hook',
}
