{
    'name': "OpenFire / Base",
    'version': '16.0.1.0.0',
    'author': "OpenFire",
    'category': 'OpenFire',
    'sequence': 15,
    'summary': "Base module for OpenFire",
    'website': 'https://www.openfire.fr',
    'description': """
""",
    'depends': [
        'base',
        'base_iban',
        'base_vat',
        'crm',
        'sale',
        'product',
        'mail',
        'contacts'
    ],
    'data': [
        'data/ir_cron.xml',
        'data/report_paperformat.xml',
        'security/of_base_security.xml',
        'security/ir.model.access.csv',
        'views/base_config_settings_views.xml',
        'views/mail_message_views.xml',
        'views/mail_template_views.xml',
        'views/mail_views.xml',
        'views/menus_actions_views.xml',
        'views/of_connector_config_settings.xml',
        'views/of_log_message_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_bank_views.xml',
        'views/res_partner_title_views.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/templates.xml',
        'wizard/base_module_upgrade_view.xml',
        'wizard/mail_compose_message_views.xml',
        'wizard/of_popup_wizard_view.xml',
        'wizard/of_res_partner_check_duplications_views.xml',
    ],
    'external_dependencies': {
        'python': [
            'schwifty',
        ],
    },
    'assets': {
        'web.assets_backend': [
            'of_base/static/src/js/of_action_manager.js',
            'of_base/static/src/js/history_back.js',
            'of_base/static/src/less/of_base.less',
        ]
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
}
