# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "OpenFire / Questionnaires",
    "version": "16.0.1.4.0",
    "license": "AGPL-3",
    "author": "OpenFire",
    "website": "https://www.openfire.fr",
    "category": "OpenFire",
    "summary": "Gestion des questionnaires pour OpenFire (basé sur l'application Sondages)",
    "depends": ["auth_signup", "http_routing", "mail", "web_tour", "of_web_widgets", "of_base"],
    "data": [
        "security/of_survey_security.xml",
        "security/ir_rule.xml",
        "security/ir.model.access.csv",
        "views/of_survey_menus.xml",
        "views/of_survey_survey_views.xml",
        "views/of_survey_user_views.xml",
        "views/of_survey_question_answer_views.xml",
        "views/of_survey_question_views.xml",
        "views/of_survey_answers.xml",
        "templates/of_survey_templates.xml",
        "templates/of_survey_templates_management.xml",
        "templates/of_survey_templates_print.xml",
        "templates/of_survey_templates_user_input_session.xml",
    ],
    "assets": {
        "of_survey.survey_assets": [
            "web/static/lib/Chart/Chart.js",
            "of_survey/static/src/js/survey_image_zoomer.js",
            "of_survey/static/src/xml/survey_image_zoomer_templates.xml",
            "of_survey/static/src/js/survey_quick_access.js",
            "of_survey/static/src/js/survey_breadcrumb.js",
            "of_survey/static/src/js/survey_form.js",
            "of_survey/static/src/js/survey_form_pdf.js",
            "of_survey/static/src/js/survey_preload_image_mixin.js",
            "of_survey/static/src/js/survey_print.js",
            "of_survey/static/src/js/survey_result.js",
            ("include", "web._assets_helpers"),
            ("include", "web._assets_frontend_helpers"),
            "of_survey/static/libs/pdfjs/pdf.min.js",
            "of_survey/static/libs/pdfjs/pdf.worker.js",
            "of_survey/static/libs/pdfjs/pdf_viewer.js",
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "of_survey/static/src/scss/survey_templates_form.scss",
            "of_survey/static/src/scss/survey_templates_results.scss",
            "of_survey/static/src/xml/survey_breadcrumb_templates.xml",
            "of_survey/static/src/xml/survey_form_pdf_templates.xml",
        ],
        "of_survey.survey_user_input_session_assets": [
            "of_survey/static/src/js/libs/chartjs-plugin-datalabels.min.js",
            "of_survey/static/src/js/survey_session_colors.js",
            "of_survey/static/src/js/survey_session_chart.js",
            "of_survey/static/src/js/survey_session_text_answers.js",
            "of_survey/static/src/js/survey_session_manage.js",
            "of_survey/static/src/xml/survey_session_text_answer_template.xml",
        ],
        "web.assets_backend": [
            "of_survey/static/src/question_page/*",
            "of_survey/static/src/js/fields_section_one2many.js",
            "of_survey/static/src/js/fields_form_page_description.js",
            "of_survey/static/src/views/*.js",
            "of_survey/static/src/scss/survey_survey_views.scss",
            "of_survey/static/src/scss/survey_question_views.scss",
            "of_survey/static/src/scss/survey_templates_results.scss",
            "of_survey/static/src/xml/conditional_questions.xml",
            "of_survey/static/src/js/conditional_questions.js",
            "of_survey/static/src/scss/conditional_questions.scss",
        ],
        "web.dark_mode_assets_backend": [
            "of_survey/static/src/scss/*.dark.scss",
        ],
        "web.assets_tests": [],
        "web.qunit_suite_tests": [
            "of_survey/static/tests/components/*.js",
        ],
        "web.assets_common": [
            "of_survey/static/src/js/tours/survey_tour.js",
        ],
        "web.assets_frontend": [
            "of_survey/static/src/js/tours/survey_tour.js",
            "of_survey/static/src/xml/survey_images.xml",
            "of_survey/static/libs/pdfjs/viewer.css",
        ],
    },
    "external_dependencies": {
        "python": ["pypdfium2"],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
