# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': "OpenFire / Mobile",
    'version': '16.0.1.0.0',
    'license': 'AGPL-3',
    'author': "OpenFire",
    'website': "https://www.openfire.fr",
    'category': "OpenFire",
    'summary': "Module permettant l'utilisation de l'application mobile",
    'depends': [
        'of_planning',
        'of_planning_graphql',
        'graphql_base',
        'of_graphql',
        'of_equipment',
        'of_equipment_graphql',
        'of_account',
        'of_account_graphql',
        'of_sale',
        'of_sale_graphql',
        'of_crm',
        'of_crm_graphql',
        'of_planning_survey',
        'of_planning_survey_graphql',
        'of_product_brand',
        'of_product_brand_graphql',
        'of_service',
        'of_service_graphql',
        'of_survey',
        'of_survey_graphql',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_config_parameter.xml',
        'data/of_planning_intervention_section.xml',
        'data/of_planning_intervention_template.xml',
        'security/ir.model.access.csv',
        'security/of_mobile_security.xml',
        'views/res_config_settings_views.xml',
        'views/product_template_views.xml',
        'views/of_service_request_views.xml',
        'views/of_product_brand_views.xml',
        'views/calendar_event_views.xml',
        'views/of_planning_task_views.xml',
        'views/of_planning_intervention_template_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
