# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': "OpenFire / Équipement",
    'version': '16.0.2.0.0',
    'license': 'AGPL-3',
    'author': "OpenFire",
    'category': "OpenFire",
    'summary': "Gestion des équipements",
    'website': "https://www.openfire.fr",
    'depends': [
        'of_planning',
    ],
    'data': [
        'data/ir_cron.xml',
        'data/of_planning_default_intervention_template.xml',
        'data/of_equipment_intervention_report_template.xml',
        'security/ir.model.access.csv',
        'views/of_equipment_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/calendar_event_views.xml',
        'views/of_calendar_event_equipment_link_views.xml',
        'views/of_planning_intervention_template_views.xml',
        'views/of_planning_intervention_template_mixin_views.xml',
        'views/of_equipment_intervention_report_template_views.xml',
        'views/res_config_settings_views.xml',
        'views/menuitems.xml',
        'reports/report_intervention_report.xml',
        'reports/report_intervention_sheet.xml',
        'wizards/of_create_equipment_wizard_views.xml',
        'wizards/of_equipment_link_create_wizard_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
