# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': "OpenFire / ESB",
    'version': '16.0.1.0.0',
    'license': 'AGPL-3',
    'author': "OpenFire",
    'website': "https://www.openfire.fr",
    'category': "OpenFire",
    'summary': "OpenFire Entreprise Service Bus",
    'depends': [
        'queue_job',
        'web_widget_mermaid_field',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/of_esb_security.xml',
        'data/ir_cron.xml',
        'data/of_esb_type_bus.xml',
        'data/of_esb_service.xml',
        'data/of_esb_rule.xml',
        'data/res_partner.xml',
        'data/res_users.xml',
        'views/of_esb_rule_views.xml',
        'views/of_esb_bus_views.xml',
        'views/of_esb_connection_views.xml',
        'views/of_esb_security_views.xml',
        'views/of_esb_service_views.xml',
        'views/of_esb_trigger_views.xml',
        'views/of_esb_history_views.xml',
        'views/of_esb_data_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
