# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "OpenFire / Basic Interface",
    "version": "16.0.1.7.0",
    "license": "AGPL-3",
    "author": "OpenFire",
    "category": "OpenFire",
    "summary": "Module de simplification de l'interface OpenFire",
    "website": "https://www.openfire.fr",
    "depends": [
        "of_equipment",
        "of_planning_tour",
        "of_planning_view",
        "of_crm",
        "of_sale",
        "of_service",
        "of_survey",
        "base_phone",
        "base_menu_visibility_restriction",
    ],
    "data": [
        "security/of_basic_interface_security.xml",
        "views/ir_ui_menu.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/product_template_views.xml",
    ],
    "external_dependencies": {},
    "assets": {},
    "installable": True,
    "application": False,
    "auto_install": False,
}
